### ISSUE TITLE
Governance drop-down does cannot be fully accessed when Getting-Started drop down is expanded. 

### ISSUE THREAD

**Issue by bchen28** [tremor-rs/tremor-www#93] opened 2021-09-29 02:24 UTC
<img width="298" alt="Screen Shot 2021-09-28 at 10 21 34 PM" src="https://user-images.githubusercontent.com/50277704/135192332-f8448a89-32fc-4707-b812-ae38260eaa97.png">

See image above. When the Getting Started drop-down is expanded, the Governance drop-down can't fully expand, and the policies tab is inaccessible.

**Comment by Licenser** [comment] 2021-09-29 08:44
Can you share which system and browser that happens in? I couldn't reproduce it on the combinations I tried

**Comment by bchen28** [comment] 2021-09-29 13:04
I'm using Google Chrome v 93.0.4577.82 and MacOS

**Comment by Licenser** [comment] 2022-05-20 12:33
This is resolved in the v12 refresh

**Closed by Licenser** 2022-05-20 12:33 UTC
